backend:
  name: git-gateway
  branch: main
  
media_folder: "images/uploads"
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "prednasky" # Jaká bude cesta ke kolekci v administraci,např. /admin/collections/novinky
    label: "Přednášky" # Jak se kolekce jmenuje v UI administrace
    folder: "prednasky" # Ve které složce jsou stránky/příspěvky uložené v Eleventy
    create: true # Uživatel může přidávat nové stránky/příspěvky (nebo false, pokud nemůže)
    slug: "{{slug}}" # Šablona jmen souborů, např. YYYY-MM-DD-title.md
    fields: # Pole, která budeme editovat. Obvykle data uložená ve front matter
      - {label: "Přednášející", name: "title", widget: "string"}
      - {label: "Fotografie", name: "foto", widget: "image"}
      - {label: "Tagy", name: "tags", widget: "hidden", default: "prednasky"}
      - {label: "Obsah", name: "body", widget: "markdown"}

  - name: "jarmark" # Jaká bude cesta ke kolekci v administraci,např. /admin/collections/novinky
    label: "Jarmark" # Jak se kolekce jmenuje v UI administrace
    folder: "jarmark" # Ve které složce jsou stránky/příspěvky uložené v Eleventy
    create: true # Uživatel může přidávat nové stránky/příspěvky (nebo false, pokud nemůže)
    slug: "{{slug}}" # Šablona jmen souborů, např. YYYY-MM-DD-title.md
    fields: # Pole, která budeme editovat. Obvykle data uložená ve front matter
      - {label: "Prodávající", name: "title", widget: "string"}
      - {label: "Fotografie", name: "foto", widget: "image"}
      - {label: "Tagy", name: "tags", widget: "hidden", default: "jarmark"}
      - {label: "Obsah", name: "body", widget: "markdown"}

